name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          
      - name: Change directory to hotel
        run: cd hotel

      - name: Build with Maven
        run: mvn clean install
        working-directory: hotel

      - name: Run tests
        run: mvn test
        working-directory: hotel

      - name: Build JAR
        run: mvn package
        working-directory: hotel

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-hotel-app
          path: hotel/target/*.jar
